name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - release
    paths:
      - 'client/**'
  pull_request:
    branches:
      - main
    paths:
      - 'client/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies and Build
      working-directory: ./client
      run: |
        npm install
        npx webpack
